### ISSUE TITLE
Crashes throwing exceptions:

### ISSUE THREAD

**Issue by user1138** [HaiyangXu/osm-bundler#3]
##### **System specs:**
**OS:** Xubuntu 14.04
**Desktop:** XFCE 4.10
**Package:** osm-bunlder (version unknowable, or suggest a method for determining this)

**Description of problem:**
On executing the RunBundler.py module using the following syntax:
```
 python RunBundler.py --photos="/home/username/archives/projects.photogammetry/buckle"
```
...where "username" is a generic placeholder for any user name in order to keep this post relevent for all readers. After the above command is executed, the following output and error messages are given:
```
Working directory created: /tmp/osm-bundler-RxPXLj
BundlerMatching executable path: /media/WD1001_vol-03/programs/osm-bundler/software/bundler/bin/KeyMatchFull
Sift executable path: /media/WD1001_vol-03/programs/osm-bundler/software/vlfeat/bin/glx/sift

Processing photo 'IMG_7205.JPG':
	Copy of the photo has been scaled down to 1200x900
	Extracting features with the SIFT method from VLFeat library...
Traceback (most recent call last):
  File "RunBundler.py", line 9, in <module>
    manager.preparePhotos()
  File "/media/WD1001_vol-03/programs/osm-bundler/osmbundler/__init__.py", line 121, in preparePhotos
    self._preparePhoto(photoInfo)
  File "/media/WD1001_vol-03/programs/osm-bundler/osmbundler/__init__.py", line 176, in _preparePhoto
    self.extractFeatures(photo)
  File "/media/WD1001_vol-03/programs/osm-bundler/osmbundler/__init__.py", line 244, in extractFeatures
    self.featureExtractor.extract(photo, self.photoDict[photo])
  File "/media/WD1001_vol-03/programs/osm-bundler/osmbundler/features/siftvlfeat.py", line 16, in extract
    subprocess.call([self.executable, "%s.jpg.pgm" % photo, "-o", "%s.key" % photo])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

**Questions:**
1.) Why are these errors happening?
2.) Is there any way to work arround these errors or fix them?

While I wait for the answers, I will try downloading the version found on this github page and try again, but it should be noted that this is the version I might already be using.

**Comment by HaiyangXu** [comment]
It seems that you have no permission to mkdir  at  /media/WD1001_vol-03/programs/ 
the procedure assume to create a 'output' directory  at the current  path as  working directory

you may put the code directory to your home directory rather than    /media/WD1001_vol-03/

you can see the code in *osm-bundler/osmbundler/__init__.py *  at line 86~ 93,it may help you out
  
            #self.workDir = os.getcwd() +'/output'
        try:
            os.mkdir('output')
            self.workDir = tempfile.mkdtemp(prefix="osm-bundler-",dir=os.path.join(os.getcwd() ,'output'))
        except OSError :
            if os.path.isdir(self.workDir):
                pass
            else: print "Cannot create output directory at "+ self.workDir

**Comment by user1138** [comment]
"HaiyangXu commented 8 hours ago
It seems that you have no permission to mkdir at /media/WD1001_vol-03/programs/"

That is a good guess but is completely incorrect. The "Programs" folder is a link located in the home directory of the principle users account that points to the "/media/WD1001_vol-03/programs/" of which that principle user has both group and ownership, read and write permissions on all of the files and folders located within the /media/WD1001_vol-03/ mount point for that partition as well as ownership of the partition itself. This link was necessary to prevent data loss during OS re-installations and as such all files in the home folder are located at the partition in question. In other words /media/WD1001_vol-03/ is the home directory and as such the files can't be moved there because they already are there.

I have no recourse for determining why the code will not create an output directory. Any help would still be appreciated.

I understand how busy you are with many other projects and I sincerely appreciate your time and continued effort towards helping resolve this issue. Thank you for your continued support.

**Comment by HaiyangXu** [comment]
Try to put the code in `  ~/`
not in  /media/WD1001_vol-03/   this may be  a windows partition ?

**Comment by user1138** [comment]
WD1001_vol-03 is not a windows partition. WD stands for Western Digital which is the brand name of a hard drive manufacturing corporation. I created that partition as the home directory in order to prevent data loss on OS re-installations. Any attempt to move a file from ~/ to /media/WD1001_vol-03/ is the same operation as copying a file or folder over itself.

In other words the code is already in the home directory and read and write permissions are enabled for that entire partition and all of its contents.

**Comment by HaiyangXu** [comment]
i donot konw why it cannot mkdir. I give you an simple way may fix.
just replace the code     *osm-bundler/osmbundler/init.py * at line 86~ 93    

    #self.workDir = os.getcwd() +'/output'
    try:
        os.mkdir('output')
        self.workDir = tempfile.mkdtemp(prefix="osm-bundler-",dir=os.path.join(os.getcwd() ,'output'))
    except OSError :
        if os.path.isdir(self.workDir):
            pass
        else: print "Cannot create output directory at "+ self.workDir

to 

     self.workDir = os.getcwd() +'/output'


and make a empty directory 'output' at the root of the code dirctory

**Comment by user1138** [comment]
1.) I have done as you have suggested by commenting out the code from line 86~89, and uncommenting line 85 to activate "self.workDir = os.getcwd() +'/output'".
2.) I checked and there IS already a directory "~/osm-bundler-master/output".
2.) I executed the RunBundler.py command and got the following traceback with the error "no such file or directory":
```
python RunBundler.py --photos="/home/username/Archives/projects.photogammetry/buckle_background_removed"
Working directory created: /home/username/osm-bundler-master/output
BundlerMatching executable path: /home/username/osm-bundler-master/software/bundler/KeyMatchFull
Sift executable path: /home/username/osm-bundler-master/software/vlfeat/sift

Processing photo 'IMG_7171.jpg':
	Copy of the photo has been scaled down to 1200x900
	Extracting features with the SIFT method from VLFeat library...
Traceback (most recent call last):
  File "RunBundler.py", line 9, in <module>
    manager.preparePhotos()
  File "/home/username/osm-bundler-master/osmbundler/__init__.py", line 167, in preparePhotos
    self._preparePhoto(photoInfo)
  File "/home/username/osm-bundler-master/osmbundler/__init__.py", line 277, in _preparePhoto
    self.extractFeatures(photo)
  File "/home/username/osm-bundler-master/osmbundler/__init__.py", line 344, in extractFeatures
    self.featureExtractor.extract(photo, self.photoDict[photo])
  File "/home/username/osm-bundler-master/osmbundler/features/siftvlfeat.py", line 16, in extract
    subprocess.call([self.executable, "%s.jpg.pgm" % photo, "-o", "%s.key" % photo])
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by HaiyangXu** [comment]
have you notice that " Extracting features with the SIFT method from VLFeat library..." 
It seems there is no vlfeat sift execute

**Comment by HaiyangXu** [comment]
have a look at osm-bundler/osmbundler/defaults.py  

featureExtractor = "siftvlfeat"    #siftvlfeat  siftlowe 

change to 
featureExtractor = "siftlowe" 


sorry for the bad documents ....

**Comment by user1138** [comment]
Thank you for the response. I almost forgot about this thread but I appreciate how much work you are doing and I'm thankful you continue to come back to help me.

I have changed the following line in "osm-bundler-master/osmbundler/defaults.py" to:
featureExtractor = "siftlowe"    #Options: siftvlfeat or siftlowe

...but we have a new problem. I think it would be best if we tested this using a set of photo's that are known to produce good results. Is there any way you could provide me with a set of photo's for the purposes of testing this out or a link to some photo's that you know work well?

I would like to know that you and I are getting the same expected results, and I've tried searching for photo's but no one appears to be sharing the original sets only the final results. Any help would be appreciated.

**Comment by user1138** [comment]
1st please let me know if the request I made in the previous post is doable.

2nd I tried again using the photographs that I made. I moved these photo's to "/home/username/temp" to make things easier to debug. I ran the "RunBundler.py" python script from the "/home/username/temp" directory. Here is a complete copy and past showing both the operation and its output:
```
~/temp$ python /home/username/osm-bundler-master/RunBundler.py --photos="/home/username/temp"
Working directory created: /home/username/temp/output
BundlerMatching executable path: /home/username/osm-bundler-master/software/bundler/KeyMatchFull
Sift executable path: /home/username/osm-bundler-master/software/sift-lowe/sift
Traceback (most recent call last):
  File "/home/username/osm-bundler-master/RunBundler.py", line 9, in <module>
    manager.preparePhotos()
  File "/home/username/osm-bundler-master/osmbundler/__init__.py", line 152, in preparePhotos
    self.bundlerListFile = open(os.path.join(self.workDir,bundlerListFileName), "w")
IOError: [Errno 2] No such file or directory: '/home/username/temp/output/list.txt'
~/temp$ ls
img_7145.jpg  img_7158.jpg  img_7170.jpg  img_7182.jpg  img_7196.jpg  img_7208.jpg  img_7220.jpg
img_7146.jpg  img_7159.jpg  img_7171.jpg  img_7183.jpg  img_7197.jpg  img_7209.jpg  img_7221.jpg
img_7147.jpg  img_7160.jpg  img_7172.jpg  img_7184.jpg  img_7198.jpg  img_7210.jpg  img_7222.jpg
img_7148.jpg  img_7161.jpg  img_7173.jpg  img_7187.jpg  img_7199.jpg  img_7211.jpg  img_7223.jpg
img_7150.jpg  img_7162.jpg  img_7174.jpg  img_7188.jpg  img_7200.jpg  img_7212.jpg  img_7224.jpg
img_7151.jpg  img_7163.jpg  img_7175.jpg  img_7189.jpg  img_7201.jpg  img_7213.jpg  img_7225.jpg
img_7152.jpg  img_7164.jpg  img_7176.jpg  img_7190.jpg  img_7202.jpg  img_7214.jpg  img_7226.jpg
img_7153.jpg  img_7165.jpg  img_7177.jpg  img_7191.jpg  img_7203.jpg  img_7215.jpg  img_7227.jpg
img_7154.jpg  img_7166.jpg  img_7178.jpg  img_7192.jpg  img_7204.jpg  img_7216.jpg  img_7228.jpg
img_7155.jpg  img_7167.jpg  img_7179.jpg  img_7193.jpg  img_7205.jpg  img_7217.jpg  img_7229.jpg
img_7156.jpg  img_7168.jpg  img_7180.jpg  img_7194.jpg  img_7206.jpg  img_7218.jpg  img_7230.jpg
img_7157.jpg  img_7169.jpg  img_7181.jpg  img_7195.jpg  img_7207.jpg  img_7219.jpg  img_7231.jpg
~/temp$
```
Where above "~/temp$" is the command prompt, and again "username" is a placeholder for the users name to keep things generic and applicable to any one who may be following this thread.

**Comment by zhenninglim** [comment]
Depending on the os you use. For 64bit system you need to find the 32bit libs such as ia-32libs in Ubuntu. Without the 32bit libraries the executwble won't run. Hence no proccessed files generated which leads to the error no files or directory

**Comment by iredmedia** [comment]
In case anyone gets here after 2020, I resolved this issue with:

`sudo apt-get install lib32z1`

As stated above, 32bit libs did not exist.

Reference: https://support.humblebundle.com/hc/en-us/articles/202759400-Installing-32-bit-libs-on-a-64-bit-Linux-system
