### ISSUE TITLE
No such file or directory: 'list.rd.txt'

### ISSUE THREAD

**Issue by villa9393** [HaiyangXu/osm-bundler#6]
Hi Haiyang,

i encounter another error as below

Performing Bundler2PMVS conversion...
Error opening file list.txt for reading
Error opening file pmvs/bundle.rd.out for reading
Num cameras: 0
Running Bundle2PMVS to generate geometry and converted camera file
Running RadialUndistort to undistort input images
Running Bundle2Vis to generate vis.dat
Traceback (most recent call last):
File "RunPMVS.py", line 10, in 
manager.doBundle2PMVS()
File "c:\Users\villa\Desktop\osm-bundler\osm-bundlerWin64\osmpmvs_init_.py", line 86, in doBundle2PMVS
undistortTextFile = open("list.rd.txt", "r")
IOError: [Errno 2] No such file or directory: 'list.rd.txt'

Any idea how to solve it?

Many thanks in advance

**Comment by admoraes** [comment]
I m having the same problem

**Comment by erdincK-61** [comment]
You probably showed the wrong path as the "bundlerOutputPath". 
After running the code 
$ RunBundler.py --photos="./examples/MyPhotos" 
a folder will be created. Try to use this folder's path as the "bundlerOutputPath". You will see some txt, gz, and jpg files in this folder. There will also be a "list.txt" file. 
If you choose the bundle folder's path as the "bundlerOutputPath", you will keep getting this error.

**Comment by wfrm** [comment]
hi you must add to ld_library path to libANN_char.so

https://github.com/HaiyangXu/osm-bundler

**Comment by wfrm** [comment]
Note for Linux

remember to set LD_LIBRARY_PATH to libANN_char.so ,otherwise KeyMatchFull may not find the library and crash

**Comment by well-hello-there** [comment]
![image](https://user-images.githubusercontent.com/51788215/74595617-134c7f00-5044-11ea-9c44-72a16b49891e.png)

After setting the LD_LIBRARY_PATH (see picture above) I'm still having this issue. Did anyone find a solution for this?
